# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Configuration for file paths. The keys are glob patterns to match to file
# paths relative to the repository root. The values are the configurations for
# the file paths. Note that the path separator is always '/'.
paths:
  .github/workflows/**/*.{yml,yaml}:
    # TODO: These are real and should be fixed eventually.
    ignore:
      - "shellcheck reported issue in this script: SC2038:.+"
      - "shellcheck reported issue in this script: SC2046:.+"
      - "shellcheck reported issue in this script: SC2086:.+"
      - "shellcheck reported issue in this script: SC2193:.+"
